<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="Expires" content="0">
  <meta http-equiv="Last-Modified" content="0">
  <meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
  <meta http-equiv="Pragma" content="no-cache">
  <title><?=$this->view->model->getText()->artesanos?>  <?=$this->view->model->getText()->software?></title>
  <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
  <meta name="keywords" content="desarrollo, paginas, web, php, html5, java, javascript, marketing, seo, consultoría, paginas en Bogotá">
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,300|Raleway:300,400,900,700italic,700,300,600">
  <link rel="stylesheet" type="text/css" href="<?=$this->view->libs;?>css/jquery.bxslider.css">
  <link rel="stylesheet" type="text/css" href="<?=$this->view->libs;?>css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="<?=$this->view->libs;?>css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="<?=$this->view->libs;?>css/animate.css">
  <link href="<?=$this->view->libs;?>hover/css/hover.css" rel="stylesheet" media="all">
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" media="all">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" media="screen" href="<?=$this->view->libs;?>css/style.css">
  <link rel="stylesheet" media="screen" href="<?=$this->view->libs;?>css/base.css">
  <script src="<?=$this->view->libs;?>js/prefixfree.min.js"></script>
<!-- Global site tag (gtag.js) - Google AdWords: 804659182 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-804659182"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-804659182');
</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119039803-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-119039803-1');
</script>
</head>
<body>
<div class="loader"></div>
<div id="home"></div>
<header>
          <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <a class="navbar-brand logo" data-href="home" onclick="goIt(this,'<?=$this->view->location?>')">
                  <img src="<?=$this->view->imgSources?>logo.png" class="logo"/>
                  <font class="logo-text">
                    <?=$this->view->model->getText()->artesanos?> 
                      <span class="logo-dec">
                        <?=$this->view->model->getText()->software?>
                      </span>
                  </font>
                </a>
              </div>
              <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                  <li class="active">
                    <a data-href="home" onclick="goIt(this,'<?=$this->view->location?>')">
                      <?=$this->view->model->getText()->inicio?>
                    </a>
                  </li>
                   <li>
                    <a data-href="servicios" onclick="goIt(this,'<?=$this->view->location?>')">
                      <?=$this->view->model->getText()->servicios?>
                    </a>
                  </li>
                  <li>
                    <a data-href="quienessomos" onclick="goIt(this,'<?=$this->view->location?>')">
                      <?=$this->view->model->getText()->quienessomos?>
                    </a>
                  </li>
                  <li>
                    <a data-href="portafolio" onclick="goIt(this,'<?=$this->view->location?>')">
                      <?=$this->view->model->getText()->potafolio?>
                    </a>
                  </li>
                  <li>
                    <a data-refresh="true" data-href="portaldeservicios" onclick="goIt(this,'<?=$this->view->location?>')">
                      <?=$this->view->model->getText()->portaldeservicios?>
                    </a>
                  </li>
                  <li>
                    <a data-href="contacto" onclick="ligboxForm()">
                      <?=$this->view->model->getText()->contacto?>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        </header>