<section class="service-description">
    <article class="slider col-md-12">
        <div>
            <p>
                <span data-top="2,2" data-right="auto,auto" data-left="-30,66.6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="200" data-timein="100" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#ffbf00" data-transformout="rotate(-360deg)">
                    somos
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,72.5" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="300" data-timein="200" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="blue" data-transformout="rotate(-360deg)">
                    una 
                </span>
            <span data-top="2,2" data-right="auto,auto" data-left="-30,76.5" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="400" data-timein="300" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="red" data-transformout="rotate(-360deg)">
                    Agencia
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,83.3" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="500" data-timein="400" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#ffbf00" data-transformout="rotate(-360deg)">
                    100%
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,88.6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="600" data-timein="500" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="red" data-transformout="rotate(-360deg)">
                   Colombiana
                </span>

                <span data-top="-50,2" data-right="auto,auto" data-left="10,6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="600" data-timein="200" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#477cc5" data-transformout="rotateX(-360deg)">
                    ¿ Buscas hacer crecer tu negocio ?
                </span>


                <span data-top="-50,14" data-right="auto,auto" data-left="10,45" data-bottom="auto,auto" data-transform="rotate(0deg)" data-opacity="1" data-timeout="800" data-timein="200" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#383838" data-transformout="rotateX(0deg)">
                   ¿ Eres una empresa bien constituida ?
                </span>

                <span data-top="-50,35" data-right="auto,auto" data-left="10,30" data-bottom="auto,auto" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="900" data-timein="300" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#46ac2a" data-transformout="rotateX(-360deg)">
                   ¿ O tal vez eres un nuevo emprendedor ?
                </span>

                <span data-top="38,38" data-right="auto,auto" data-left="150,6" data-bottom="auto,auto" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1000" data-timein="400" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#477cc5" data-transformout="rotateX(-360deg)">
                    Cualquiera que sea el caso
                </span>


                <span data-top="auto,auto" data-right="auto,auto" data-left="10,6" data-bottom="-50,39" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1100" data-timein="500" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#383838" data-transformout="rotateX(-360deg)">
                    Nuestros expertos
                </span>

                 <span data-top="auto,auto" data-right="auto,auto" data-left="10,36" data-bottom="-50,27.4" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1200" data-timein="600" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#46ac2a" data-transformout="rotateX(-360deg)">
                    Están a tu disposición
                </span>

                <img data-headerlogo="#fff" data-headerlogodes="#fff" data-header="#000" data-headertext="#fff" data-weightheader="400" data-btnservice="#46ac2a" data-ligboxform="#0b2a6a" data-ligboxbth="#187ed6" data-ligboxborder="#fff" data-footer="#304d8f" data-footerbtn="#187ed6" data-footerborder="#187ed6" data-controls="#304d8f" data-controlspck="#fff" src="https://www.000webhost.com/static/default.000webhost.com/images/banner-homepage.jpg" />
            </p>
            <!--
            <p>
                <span data-top="2,2" data-right="auto,auto" data-left="-30,66.6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="200" data-timein="100" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#ffbf00" data-transformout="rotate(-360deg)">
                    somos
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,72.5" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="300" data-timein="200" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="blue" data-transformout="rotate(-360deg)">
                    una 
                </span>
            <span data-top="2,2" data-right="auto,auto" data-left="-30,76.5" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="400" data-timein="300" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="red" data-transformout="rotate(-360deg)">
                    Agencia
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,83.3" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="500" data-timein="400" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#ffbf00" data-transformout="rotate(-360deg)">
                    100%
                </span>
                 <span data-top="2,2" data-right="auto,auto" data-left="-30,88.6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="600" data-timein="500" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="red" data-transformout="rotate(-360deg)">
                   Colombiana
                </span>

                <span data-top="-50,2" data-right="auto,auto" data-left="10,6" data-bottom="auto,auto" data-transform="rotate(360deg)" data-opacity="1" data-timeout="600" data-timein="200" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#477cc5" data-transformout="rotateX(-360deg)">
                    Conoce lo que la publicidad en línea puede hacer por ti
                </span>


                <span data-top="-50,14" data-right="auto,auto" data-left="10,6" data-bottom="auto,auto" data-transform="rotate(0deg)" data-opacity="1" data-timeout="800" data-timein="200" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#383838" data-transformout="rotateX(0deg)">
                   Hacemos campañas en: 
                </span>

                <span data-top="-50,26" data-right="auto,auto" data-left="10,6" data-bottom="auto,auto" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="900" data-timein="300" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#46ac2a" data-transformout="rotateX(-360deg)">
                    Google Adwords y la red de contenidos de google
                </span>

                <span data-top="38,38" data-right="auto,auto" data-left="150,6" data-bottom="auto,auto" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1000" data-timein="400" data-easing="easeOutBounce" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#477cc5" data-transformout="rotateX(-360deg)">
                    En youtube
                </span>


                <span data-top="auto,auto" data-right="auto,auto" data-left="10,6" data-bottom="-50,39" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1100" data-timein="500" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#383838" data-transformout="rotateX(-360deg)">
                    En twitter, instagram y snapchat
                </span>

                 <span data-top="auto,auto" data-right="auto,auto" data-left="10,6" data-bottom="-50,27.4" data-transform="rotateX(360deg)" data-opacity="1" data-timeout="1200" data-timein="600" data-easing="easeInOutBack" data-timeoutout="500" data-transition="all 500ms cubic-bezier(0.68, -0.55, 0.265, 1.55)" data-background="#46ac2a" data-transformout="rotateX(-360deg)">
                    Los mejores profesionales certificados a tu servicio
                </span>

                <img data-headerlogo="#fff" data-headerlogodes="#fff" data-header="#304d8f" data-headertext="#fff" data-weightheader="400" data-btnservice="#46ac2a" data-ligboxform="#0b2a6a" data-ligboxbth="#187ed6" data-ligboxborder="#fff" data-footer="#304d8f" data-footerbtn="#187ed6" data-footerborder="#187ed6" data-controls="#304d8f" data-controlspck="#304d8f" src="http://www.mooncakes.fi/img/facebook-logo.jpg" />
            </p>
            -->
        </div>
        <div>
            <div>
                <p class="glyphicon glyphicon-chevron-left"></p>
                <p class="glyphicon glyphicon-chevron-right"></p>
            </div>
            <div>
                <ol>
    <li>
        <span class="a"><span>
      <font class="service-title">NUESTRO SERVICIO PUEDE INCLUIR</font>
      <font class="service-price">A Partir de 199.999 $CO</font>
      <ol>
         <li>asesoría por un experto</li>
         <li>apoyo en levantamiento de información</li>
         <li>Investigación de mercado</li>
         <li>Diseño y creación de perfiles</li>
         <li><font class="service-sub-title">Implementación de campañas de marketing en las principales redes sociales como:</font>
            <ol>
                <li>Facebook</li>
                <li>Canales de youtube</li>
                <li>Cuentas de google</li>
                <li>Twitter</li>
                <li>Instagram</li>
                <li>Entre otros</li>
            </ol>
         </li>
         <li><font class="service-sub-title">Publicaciones periódicas de nuevo contenido de forma:</font>
            <ol>
                <li>Semanal</li>
                <li>Mensual</li>
                <li>Trimestral</li>
                <li>O por acuerdo en mutuas partes</li>
            </ol>
         </li>
         <li>Respuesta directa a sus clientes o como prefieras</li>
         <li>Reporte semanal con estadísticas del proceso</li>
         <li><font class="service-sub-title">Un tope mínimo de nuevos clientes potenciales de forma:</font>
            <ol>
                <li>Semanal</li>
                <li>Mensual</li>
                <li>Trimestral</li>
                <li>O por acuerdo en mutuas partes</li>
            </ol>
         </li>
         <li><font class="service-sub-title">Administración de todas tus redes sociales como:</font>
            <ol>
                <li>Facebook</li>
                <li>Canales de youtube</li>
                <li>Cuentas de google</li>
                <li>Twitter</li>
                <li>Instagram</li>
                <li>Entre otros</li>
            </ol>
         </li>
         <li>Estudio de la competencia</li>
         <li>Y si nada de esto logra llamar tu atencion llamanos sin costo alguno y armemos tu paquete juntos</li>
      </ol>

      <a onclick="ligboxForm()">Quiero más información</a>
                            </span>
        <span><font class="argument">Descripción del Servicio </font>

<font class="jump"></font>
<font class="big-letter">C</font>rear una estrategia o campaña publicitaria en las diferentes redes sociales como: <font class="key-word">Facebook , Twitter, Youtube, Blogs Corporativos y otras redes sociales</font> donde los usuarios de internet están interactuando diariamente.
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">L</font>as <font class="key-word">redes sociales</font> se han convertido en una <font class="key-word">herramienta indispensable</font> para toda empresa y estar presente en ella <font class="key-word">te dará grandes beneficios</font> , de la misma forma las <font class="key-word">redes sociales</font> son tu mejor aliado para <font class="key-word">promocionar tus marcas o productos</font> con el voz a voz , cuando una persona le gusta un producto que publiques en <font class="key-word">redes sociales</font> todos sus amigos lo van a ver y de esta manera se <font class="key-word">multiplica el número de usuarios</font> que están viendo e interactuando con tu <font class="key-word">empresa cada dia</font>.
 
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">E</font>n Artisans Ofrecemos diferentes planes de <font class="key-word">administración de redes sociales</font> , esta <font class="key-word">estrategia publicitaria</font> es ideal para que su empresa haga contacto con <font class="key-word">sus clientes potenciales</font> y, ayudarán a la recordación de marca y dará a conocer su empresa de una <font class="key-word">forma rápida y efectiva a nivel local, nacional e internacional</font>.
<font class="jump"></font>
<font class="argument">¿ que esperas ?</font>
<font class="jump"></font>
<font class="big-letter">N</font>o dudes en contactarnos para obtener mayor información estamos dispuestos a ayudarte,
puedes contactarnos por <font class="contact-us">info@artisanssoftware.com</font>, puedes llamarnos directamente desde este sitio web <font class="contact-us">totalmente gratis</font> o contactarnos al <font class="contact-us">pbx: 378 40 37 cel.corporativo: 312 442 11 62</font></span>
        </span>
    </li>
</ol>
            </div>
        </div>
        <div>
            <div></div>
        </div>
        <div>
            <!--
            <img src="<?=$this->imgSources?>logo2.png" />
        -->
            <p>
                <input type="text" placeholder="Digita en este campo lo que desees buscar :)">
                <button class="glyphicon glyphicon-search"></button>
            </p>
        </div>
        <a class="control-left">
            <div>
                <img>
                <p class="glyphicon glyphicon-chevron-left"></p>
            </div>
        </a>
        <a class="control-right">
            <div>
                <img>
                <p class="glyphicon glyphicon-chevron-right"></p>
            </div>
        </a>
    </article>
    <div class="container">
        <article class="col-md-8">
            <h1>MARKETING DIGITAL</h1>
            <h3>
            <font class="big-letter">S</font>i estas buscando ampliar tu<font class="key-word"> negocio </font> conseguir nuevos <font class="key-word">clientes potenciales</font> de <font class="key-word">forma periódica y efectiva</font> has llegado al sitio correcto, permítenos presentarnos.
<font class="jump"></font><font class="jump"></font>
<font class="argument"> ¿ quienes somos ?</font>
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">A</font>rtisans es una empresa especializada implementando campañas de <font class="key-word">marketing digital</font> y en <font class="key-word">redes sociales</font> nosotros podemos hacerte crecer a ti y tu negocio de una <font class="key-word">forma extraordinaria</font>.
<font class="jump"></font><font class="jump"></font>
<font class="argument">¿ para que esto ?</font> 
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">E</font>l <font class="key-word">marketing digital</font> juega un papel clave al momento de obtener <font class="key-word">nuevos clientes</font> los cuales adquieren tus <font class="key-word">productos y servicios</font> de igual modo la <font class="key-word">empresa que te brinda este servicio</font> también cumple un <font class="key-word">rol vital</font> al momento de ayudarte a alcanzar tus <font class="key-word">objetivos</font> como <font class="key-word">emprendedor o empresario</font>, trabajar con el <font class="key-word">personal certificado</font> por empresas como <font class="key-word">google, facebook entre otros</font>, personal el cual tenemos en <font class="key-word">Artisans</font> te brinda la <font class="key-word">garantía</font> de que las cosas se harán bien con una <font class="key-word">mínima inversión de presupuesto</font> la cual te ayudará llegar a tu <font class="key-word">público objetivo</font>.
<font class="jump"></font><font class="jump"></font>
<font class="argument">¿ qué hacemos y cómo lo hacemos ?</font>
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">P</font>ara ello nosotros primeramente hacemos una <font class="key-word">investigación de mercado</font> en caso de que desees comercializar algún nuevo <font class="key-word">producto o servicio</font> la <font class="key-word">investigación de mercado</font> la hacemos con el fin de crear una <font class="key-word">estrategia de marketing completamente personalizada para el cliente</font> sin importar si eres una empresa con trayectoria o no nosotros aseguramos la calidad del servicio.
<font class="jump"></font><font class="jump"></font>
<font class="argument">¿ personal a tu servicio ?</font>
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">S</font>omos una empresa <font class="key-word">google partners</font> poseemos personal <font class="key-word">certificado</font> <font class="key-word">implementando estrategias de marketing digital en display, en la red de contenidos de google, en youtube, en twitter, en facebook</font> y en general en todos los medios digitales que nos sea posible todo con el fin de lograr el objetivo principal el cual es satisfacer las necesidades del cliente.
<font class="jump"></font><font class="jump"></font>
<font class="big-letter">S</font>i quieres saber más no dudes en contactarnos nuestros agentes están esperando tu llamada.
<font class="jump"></font>
            <font class="argument">¿ Que esperas para trabajar con nosotros ?</font>
<font class="jump"></font>
<font class="big-letter">N</font>o dudes en contactarnos para obtener mayor información estamos dispuestos a ayudarte,
puedes contactarnos por <font class="contact-us">info@artisanssoftware.com</font>, puedes llamarnos directamente desde este sitio web <font class="contact-us">totalmente gratis</font> o contactarnos al <font class="contact-us">pbx: 378 40 37 cel.corporativo: 312 442 11 62</font>
        </h3>


        
        </article>
        <article class="col-md-4">
        </article>
    
<article class="datos-pago col-md-12">
    <img src="https://cirujanos-plasticos.com.co/wp-content/uploads/2017/07/metodos-de-pago-por-payu.png">
</article>
</div>
</section>








